#!/bin/bash
#Sabryr 06-11-2020
V=0.1

function call_ffmpeg(){
	split_arr=("$@")
	if [[ "${#split_arr[@]}" > 0 ]]
	then
		echo "OK"
	else
		echo "Nothing to split, check the timing file"
	fi
}

function fabricate_ffmpeg() {
	ffmpeg_split_arr=()
	while IFS=  read -r line
		do
		  # take action on $line #
		if [[ "$line" != \#* ]]
		then
			IFS="," read -ra time_arr <<< "$line"
			if [[ "${#time_arr[@]}" == 2 ]]
			then
				# ffmpeg -ss 00:00:00 -to 00:50:00 -i largefile.mp4 -acodec copy -vcodec copy smallfile.mp4
				split_name="${time_arr[0]}-${time_arr[1]}-$1"
				#echo "ffmpeg -ss ${time_arr[0]} -to ${time_arr[1]} - $1 -acodec copy -vcodec copy ${split_name}"
				ffmpeg_split_arr+=("ffmpeg -ss ${time_arr[0]} -to ${time_arr[1]} - $1 -acodec copy -vcodec copy ${split_name}")
			else
				echo "Error in line $line expected format START_TIME,END_TIME"
			fi
		fi
	done < $2
	call_ffmpeg "${ffmpeg_split_arr[@]}"
 	#ffmpeg -i $1 -ss 0 -t 600 first-10-min.m4v
}


ffmpeg --help &>/dev/null
if [ $? -eq 0 ]
then
	#echo "ffmpeg found"
	if [ $# -le 1 ]
	then
		echo "Please propvide video file to split and timinig file"
	else
		#echo $@
		if [[ -f "$1" ]]
		then
			#echo "Video file "$1
			if [[ -f "$2" ]]
			then
				#echo "Timing file "$2
				fabricate_ffmpeg $1 $2
			else
				echo "invalid file " $2
			fi

		else
			echo "Invalid file " $1
		fi
	fi
else
	echo "Please install ffmpeg"
fi
